[package]
name = "dum"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "An npm scripts runner"
authors = ["EGOIST <0x142857@gmail.com>"]
homepage = "https://github.com/egoist/dum"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pico-args = "0.4.2"
serde_json = "1.0"
